name: Hourly Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Run at minute 0 of every hour

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      CRAWLER_MAX_PAGES: 100
      CRAWLER_COOKIE: ${{ secrets.CRAWLER_COOKIE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run crawler
      run: |
        python src/toutiao_crawler.py

    - name: Commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add articles
        git diff --quiet && git diff --staged --quiet || git commit -m "Update articles from crawler"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
